# Generated by Django 4.2.7 on 2023-11-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
