# Generated by Django 4.2.7 on 2023-11-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_student_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
